name: "Task"
description: "General task to be completed"
title: "[TASK] "
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "## Task Description"
  - type: textarea
    id: description
    attributes:
      label: "What needs to be done?"
      description: "Provide details of the task"
      placeholder: "E.g., Set up CI/CD pipeline"
    validations:
      required: true
  - type: input
    id: deadline
    attributes:
      label: "Deadline"
      description: "Enter date in YYYY-MM-DD format (no automatic calendar validation, e.g., 2025-09-19)."
      placeholder: "YYYY-MM-DD"
    validations:
      required: false
      pattern: "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$"

