services:
  smtp-server:
    build:
      context: .
      dockerfile: ./smtp/Dockerfile
    container_name: smtp-server-container
    environment:
      - MAIL_DOMAIN=${MAIL_DOMAIN:-example.lk}
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./silver-config/gen/postfix/main.cf:/etc/postfix/main.cf:ro
      - ./silver-config/static/postfix/master.cf:/etc/postfix/master.cf:ro
      - ./silver.yaml:/etc/postfix/silver.yaml
      - maildata:/var/mail/vmail
      - postfix-sasl:/var/spool/postfix/private
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./smtp/conf/virtual-domains:/etc/postfix/virtual-domains:rw
      - ./smtp/conf/virtual-users:/etc/postfix/virtual-users:rw
      - ./smtp/conf/virtual-aliases:/etc/postfix/virtual-aliases:rw
    networks:
      - mail-network
    depends_on:
      - opendkim-server
      - dovecot-server
      - rspamd-server
      - certbot-server
    security_opt:
      - no-new-privileges:true

  dovecot-server:
    build:
      context: ./imap
    container_name: dovecot-server
    ports:
      - "143:143"
      - "993:993"
      - "110:110"
      - "995:995"
    volumes:
      - ./silver-config/static/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf:ro
      - ./silver-config/static/dovecot/auth_api.lua:/etc/dovecot/auth_api.lua:ro
      - maildata:/var/mail/vmail
      - postfix-sasl:/var/spool/postfix/private
      - ./letsencrypt:/etc/letsencrypt:ro
    networks:
      - mail-network
    depends_on:
      - certbot-server
    security_opt:
      - no-new-privileges:true

  opendkim-server:
    build:
      context: .
      dockerfile: ./dkim/Dockerfile
    container_name: opendkim-server
    volumes:
      - ./silver.yaml:/etc/opendkim/silver.yaml
      - ./silver-config/static/opendkim/opendkim.conf:/etc/opendkim/opendkim.conf:ro
      - ./silver-config/gen/opendkim/KeyTable:/etc/opendkim/KeyTable:ro
      - ./silver-config/gen/opendkim/SigningTable:/etc/opendkim/SigningTable:ro
      - ./silver-config/gen/opendkim/TrustedHosts:/etc/opendkim/TrustedHosts:ro
      - dkim-keys:/etc/dkimkeys
    networks:
      - mail-network
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true

  rspamd-server:
    image: rspamd/rspamd:latest
    container_name: rspamd-server
    hostname: rspamd
    ports:
      - "11332:11332"
      - "11334:11334"
    volumes:
      - rspamd_data:/var/lib/rspamd
      - ./silver-config/static/rspamd/:/etc/rspamd/local.d:ro
      - clamsock:/var/run/clamav # shared socket volume
    networks:
      - mail-network
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true

  clamav-server:
    image: clamav/clamav:stable 
    container_name: clamav-server
    volumes:
      - clamsock:/var/run/clamav # shared socket volume
    networks:
      - mail-network
    restart: always
    depends_on:
      - rspamd-server
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true

  thunder-server:
    image: ghcr.io/asgardeo/thunder:latest
    container_name: thunder-server
    ports:
      - "127.0.0.1:8090:8090"
    networks:
      - mail-network
    volumes:
      - ./thunder/certs/server.cert:/opt/thunder/repository/resources/security/server.cert:ro
      - ./thunder/certs/server.key:/opt/thunder/repository/resources/security/server.key:ro
    depends_on:
      - certbot-server
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true

  certbot-server:
    build:
      context: ./certbot
    container_name: certbot-server
    volumes:
      - ./silver.yaml:/etc/certbot/silver.yaml:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt/certbot-logs:/var/log/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mail-network
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true

volumes:
  maildata:
  postfix-sasl:
  dkim-keys:
  rspamd_data:
  clamsock:


networks:
  mail-network:
