version: "3.9"

services:
  smtp-server:
    build:
      context: ./smtp
    container_name: smtp-server-container
    hostname: ${MAIL_DOMAIN}
    env_file:
      - smtp/conf/.env.conf
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - maildata:/var/mail/vmail
      - postfix-sasl:/var/spool/postfix/private
      - ./smtp/cert:/etc/letsencrypt/live/${MAIL_DOMAIN}:ro
      - ./smtp/cert:/etc/letsencrypt/archive/${MAIL_DOMAIN}:ro
    networks:
      - mail-network
    depends_on:
      - opendkim-server
      - dovecot-server
      - rspamd-server

  dovecot-server:
    build:
      context: ./imap
    container_name: dovecot-server
    env_file:
      - .env
    ports:
      - "143:143"
    volumes:
      - maildata:/var/mail/vmail
      - postfix-sasl:/var/spool/postfix/private
      - ./imap/cert:/etc/letsencrypt/live/${MAIL_DOMAIN}:ro
      - ./imap/cert:/etc/letsencrypt/archive/${MAIL_DOMAIN}:ro
    networks:
      - mail-network

  opendkim-server:
    build:
      context: ./dkim
    container_name: opendkim-server
    env_file:
      - .env
    volumes:
      - dkim-keys:/etc/opendkim/keys
    networks:
      - mail-network

  rspamd-server:
    image: rspamd/rspamd:latest
    container_name: rspamd-server
    hostname: rspamd
    ports:
      - "11332:11332"
      - "11334:11334"
    volumes:
      - rspamd_data:/var/lib/rspamd
      - ./spam/conf:/etc/rspamd/local.d
      - clamsock:/var/run/clamav  # shared socket volume
    networks:
      - mail-network

  clamav-server:
    image: mkodockx/docker-clamav:alpine
    container_name: clamav-server
    volumes:
      - clamsock:/var/run/clamav  # shared socket volume
    networks:
      - mail-network
    restart: always
    depends_on:
      - rspamd-server

  thunder-server:
    image: ghcr.io/asgardeo/thunder:latest
    container_name: thunder-server
    ports:
      - "8090:8090"
    networks:
      - mail-network
  mariadb:
    image: mariadb:10.11
    container_name: mariadb-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mail-network


volumes:
  maildata:
  postfix-sasl:
  dkim-keys:
  rspamd_data:
  clamsock:
  mariadb_data:

networks:
  mail-network: