services:
  smtp-server:
    build:
      context: ./smtp
    container_name: smtp-server-container
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./silver.yaml:/etc/postfix/silver.yaml
      - maildata:/var/mail/vmail
      - postfix-sasl:/var/spool/postfix/private
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./smtp/conf/virtual-domains:/etc/postfix/virtual-domains:rw
      - ./smtp/conf/virtual-users:/etc/postfix/virtual-users:rw
      - ./smtp/conf/virtual-aliases:/etc/postfix/virtual-aliases:rw
      - ./raven/data:/app/data:rw
    networks:
      - mail-network
    command: sh -c "chmod -R 0777 /app/data && /entrypoint.sh"
    depends_on:
      - opendkim-server
      - dovecot-server
      - rspamd-server
      - certbot-server

  dovecot-server:
    build:
      context: ./imap
    container_name: dovecot-server
    ports:
      - "1143:143"
      - "1142:993"
      - "110:110"
      - "995:995"
    volumes:
      - ./silver.yaml:/etc/dovecot/silver.yaml:ro
      - maildata:/var/mail/vmail
      - postfix-sasl:/var/spool/postfix/private
      - ./letsencrypt:/etc/letsencrypt:ro
    networks:
      - mail-network
    depends_on:
      - certbot-server
  
  raven-server:
    image: ghcr.io/lsflk/raven:latest
    container_name: raven
    ports:
      - "143:143"
      - "993:993"
    volumes:
      - ./raven/config:/etc/raven:rw
      - ./raven/data:/app/data:rw
      - ./raven/certs:/certs:ro
    environment:
      - DB_FILE=/app/data/mails.db
    networks:
      - mail-network
    restart: unless-stopped
    user: "0:0"

  opendkim-server:
    build:
      context: ./dkim
    container_name: opendkim-server
    volumes:
      - ./silver.yaml:/etc/opendkim/silver.yaml
      - dkim-keys:/etc/opendkim/keys
    networks:
      - mail-network
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true

  rspamd-server:
    image: rspamd/rspamd:latest
    container_name: rspamd-server
    hostname: rspamd
    ports:
      - "11332:11332"
      - "11334:11334"
    volumes:
      - rspamd_data:/var/lib/rspamd
      - ./spam/conf:/etc/rspamd/local.d
      - clamsock:/var/run/clamav
    networks:
      - mail-network

  clamav-server:
    image: clamav/clamav:latest  # Official ClamAV image
    container_name: clamav-server
    volumes:
      - clamsock:/var/run/clamav
      - clamav_db:/var/lib/clamav
    networks:
      - mail-network
    restart: always
    depends_on:
      - rspamd-server
    environment:
      - CLAMAV_NO_FRESHCLAMD=false
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

  thunder-server:
    image: ghcr.io/asgardeo/thunder:latest
    container_name: thunder-server
    ports:
      - "127.0.0.1:8090:8090"
    networks:
      - mail-network
    volumes:
      - ./thunder/certs/server.cert:/opt/thunder/repository/resources/security/server.cert:ro
      - ./thunder/certs/server.key:/opt/thunder/repository/resources/security/server.key:ro
    environment:
      - THUNDER_TLS_ENABLED=true
      - THUNDER_PORT=8090
    depends_on:
      - certbot-server

  certbot-server:
    build:
      context: ./certbot
    container_name: certbot-server
    volumes:
      - ./silver.yaml:/etc/certbot/silver.yaml:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt/certbot-logs:/var/log/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mail-network

volumes:
  maildata:
  postfix-sasl:
  dkim-keys:
  rspamd_data:
  clamsock:
  clamav_db: 
  go-imap-data:

networks:
  mail-network: